version: "3.7"

networks:
    stock_network:
        driver: bridge

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: stock_backend
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        networks:
            - stock_network

    db:
        image: mysql:5.7.22
        container_name: stock_mysql
        restart: always
        tty: true
        ports: 
            - "3307:3306"
        environment:
            MYSQL_DATABASE: stock
            MYSQL_ROOT_PASSWORD: secret
        volumes: 
            - ./docker/mysql:/var/lib/mysql
        networks:
            - stock_network
